### ISSUE TITLE
Could i get some assistance in using this please:)

### ISSUE THREAD

**Issue by mrelive** [voc/touchmix-patcher#1]
I would love to get your help in using this. it is slightly over my head , but in essence i would like to modify the connection process so it can be connected to more easily , possibly more midi control or osc control .

**Comment by florolf** [comment]
You've dug up a reaaaally old project.

Some context, since there is no README (shame on me):
 - c3voc bought a bunch of QSC TouchMix8 many years ago to use in our lecture room setup
 - This repo implements bits and pieces that can modify the firmware upgrade files for these devices so you can have custom functionality

This was just a quick hack that happened while I was bored at some event where we made lecture recordings. The only modifications that are present are:
 - Set the root password to a known value so you can SSH into the system
 - Change the update server URL to one of our systems (long since defunct) so that we can use the code in this repo to automatically apply the patches again to any new firmware that is released and have our devices update to those patched images instead of rolling back to the original vendor firmware
 - Swap out the boot logo for our logo

Except for the SSH bit, none of this is really useful and is a long way away of actually adding functionality to the actual main application, which I think is what you're trying to do? That would require a lot more reverse engineering.

Anyway, I've just checked and the bits and pieces in this repo still seem to be basically valid - the v3.0.09551 firmware image still uses the exact same format and encryption method as it did when I originally played around with it, so this is a convenient way to get a full rootfs image for the device if you want to do that reverse engineering work.

Otherwise, this is probably not really going to be useful for you. If you have specific questions, I'm happy to answer them.
